language: node_js
node_js:
  - "8.11.3"
cache:
  directories:
    - node_modules
script:
  - npm test

after_success: 
  - npm install coveralls && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js